# Inital annotation for dbSNP data to exclude COMMON SNPs

[[annotation]]
file="/betelgeuse04/analysis/utsu/resources/vcfanno/dbSNP-b156/GCF_000001405.25.singleALT.common.chrmod.sort.vcf.gz"
names=["dbSNPcommon", "rs"]
fields=["COMMON". "RS"]
ops=["flag", "self"]
